CbuRetentionAlert.Web/Controllers/LogOnController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;
using CbuRetentionAlert.Web.Models;

namespace CbuStudentLookup.Web.Controllers
{
    public class LogOnController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Index(LogOnModel model, string returnUrl)
        {
            if (ModelState.IsValid)
            {
                if (Membership.ValidateUser(model.UserName, model.Password))
                {
                    FormsAuthentication.SetAuthCookie(model.UserName, model.RememberMe);

                    if (Url.IsLocalUrl(returnUrl) && returnUrl.Length > 1 && returnUrl.StartsWith("/")
                        && !returnUrl.StartsWith("//") && !returnUrl.StartsWith("/\\"))
                    {
                        return Redirect(returnUrl);
                    }

                    return RedirectToAction("Index", "Home");
                }

                ModelState.AddModelError("", "The user name or password provided is incorrect.");
            }

            // If we got this far, something failed, redisplay form
            return View(model);
        }

        public ActionResult LogOff()
        {
            FormsAuthentication.SignOut();
            if (HttpContext.Session != null)
            {
                HttpContext.Session["userId"] = null;
                HttpContext.Session["groupIds"] = null;
                HttpContext.Session["accountId"] = null;
                HttpContext.Session["Admin"] = null;

                HttpContext.Session.Abandon();
            }

            return RedirectToAction("index", "home");
        }

    }
}

CbuRetentionAlert.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title</title>
    <link href='http://fonts.googleapis.com/css?family=Cuprum:400,400italic,700' rel='stylesheet'
        type='text/css'>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/ui")
    @Scripts.Render("~/bundles/val")
    @Scripts.Render("~/bundles/modernizr")
    @RenderSection("scripts", required: false)
</head>
<body>
    <header class="navbar navbar-fixed-top">
        <div class="navbar-inner">
            <div class="container-fluid">
                <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse"><span
                    class="icon-bar"></span><span class="icon-bar"></span><span class="icon-bar"></span>
                </a>@Html.ActionLink("OPS Retention Alerts", "index", "home", null, new { @class = "brand" })
                <div class="nav-collapse collapse">
                    @if (Request.IsAuthenticated)
                    {
                        <ul class="nav">
                            <li>@Html.ActionLink("Home", "index", "home")</li>
                           
                            @if (User.IsInRole("Admin"))
                            {
                                <li>@Html.ActionLink("Submit a New Retention Alert as Instructor", "newstep1", "alert", null, new { @onclick = "showProcessing();" })</li>
                                <li>@Html.ActionLink("Submit a New Retention Alert By Course Roster", "newbycourse", "alert", null, new { @onclick = "showProcessing();" })</li>
                                <li>
                                    <div class="btn-group">
                                        <a class="btn dropdown-toggle" data-toggle="dropdown" href="#">Reports&nbsp;<span class="caret"></span></a>
                                        <ul class="dropdown-menu">
                                            <li>@Html.ActionLink("Retention Alerts by Semester & Year", "session", "report") </li>
                                        </ul>
                                    </div>
                                </li>
                            }
                            else
                            {
                                <li>@Html.ActionLink("Submit a New Retention Alert", "newstep1", "alert", null, new { @onclick = "showProcessing();" })</li>
                            }
                        </ul>
                    }
                    <p class="navbar-text pull-right">
                        @if (Request.IsAuthenticated)
                        {
                            <text>Logged in as <strong>@User.Identity.Name</strong>! @Html.ActionLink("Log Off", "LogOff", "LogOn")</text>
                        }
                        else
                        {
                            @Html.ActionLink("Sign In", "Index", "LogOn")
                        }
                    </p>
                </div>
                <!--/.nav-collapse -->
            </div>
        </div>
    </header>
    <div class="container">
        <input type="hidden" id="navActive" value="@ViewBag.navActive" />
        @RenderBody()
    </div>
    <footer class="footer" style="display: none;">
        <p>
            &copy; @DateTime.Now.Year, California Baptist University</p>
    </footer>
    <div id="spinner" class="spinner" style="display: none;">
        <img id="img-spinner" src="@Url.Content("~/content/images/ajax-loader.gif")" alt="Loading"/>
    </div>
    <div id="mask">
    </div>
</body>
</html>