CbuRetentionAlert.Web/Controllers/AlertController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using CbuRetentionAlert.Web.Models;
using System.Text;
using CbuRetentionAlert.Web.ViewModels;

namespace CbuRetentionAlert.Web.Controllers
{
    public class AlertController : Controller
    {
        //
        // GET: /Alert/

        [Authorize]
        public ActionResult Index(int id)
        {
            if (User.IsInRole("Admin"))
            {
                AlertViewModel model = new AlertViewModel();
                model.LoadAlert(id);

                return View(model);
            }
            else
            {
                return RedirectToAction("index", "home");
            }
        }

        [Authorize]
        public ActionResult StudentAlert(int id)
        {
            
                AlertViewModel model = new AlertViewModel();
                model.LoadAlert(id);

                return View(model);
        }

        [Authorize]
        [HttpGet]
        public ActionResult New()
        {
            return View();
        }

        [Authorize]
        [HttpPost]
        public ActionResult New(string txtSFirstName, string txtSLastName, string txtSID, string txtFFirstName, string txtFLastName, string txtFEmail, string txtFID,
                                string txtCourse, string txtSection, string ddlSemester, int ddlYear, string txtAttendDate, string ddlConcern, string grade,
                                string comments, string studentContact, string instructorContact)
        {
            int studentId = -1;
            DateTime lastAttended = DateTime.Now;

            if (int.TryParse(txtSID, out studentId) && DateTime.TryParse(txtAttendDate, out lastAttended))
            {
                var retentionAlert = new Lib.Models.RetentionAlertModel();

                int facultyId = -1;

                int.TryParse(txtFID, out facultyId);

                if (retentionAlert.SaveRetentionAlert(studentId, txtFFirstName, string.Empty, txtFLastName, txtFEmail, facultyId, txtCourse, txtSection, ddlSemester, ddlYear,
                                                  lastAttended, ddlConcern, (grade == "Yes" ? true : false), comments, (studentContact == "Yes" ? true : false), (instructorContact == "Yes" ? true : false), User.Identity.Name.Replace("@calbaptist.local", ""), null))
                {
                    AlertSubmittedResultsModel model = new AlertSubmittedResultsModel();

                    model.Results = new List<SubmitResult> { new SubmitResult { StudentID = txtSID, StudentName = txtSFirstName + " " + txtSLastName, Successful = true } };

                    TempData["Results"] = model;

                    return RedirectToAction("alertsubmitted");
                }
                else
                {
                    ViewData["ErrorMessage"] = "There was an error while trying to save this retention alert, please double check the Student ID and then try again.";
                    return View();
                }
            }
            else
            {
                ViewData["ErrorMessage"] = "There was an error while trying to save this retention alert, please double check the Student ID and then try again.";
                return View();
            }
        }

        [Authorize]
        public ActionResult NewStep1()
        {
            NewAlertViewModel model = new NewAlertViewModel();

            var adUser = CbuAd.Lib.User.GetSingle(User.Identity.Name.Replace("@calbaptist.local", ""));

            if (adUser != null && !string.IsNullOrEmpty(adUser.EmployeeId))
            {
                int employeeId = -1;

                if (int.TryParse(adUser.EmployeeId, out employeeId))
                {
                    model.LoadInstructorCourses(employeeId);
                }
            }

            //model.LoadInstructorCourses(212325);

            return View(model);
        }

        [Authorize]
        [HttpGet]
        public ActionResult NewStep2(string c, string p)
        {
            NewAlertViewModel model = new NewAlertViewModel();

            model.LoadStudentEnrollments(c);

            if (!string.IsNullOrEmpty(p))
            {
                model.PreviousStep = p;
            }

            return View(model);
        }

        [Authorize]
        [HttpPost]
        public ActionResult NewStep3(string p)
        {
            string course = Request["course"];
            var studentIds = new List<string>();

            for (int i = 0; i < Request.Form.Keys.Count; i++)
            {
                if (Request.Form.Keys[i].StartsWith("chkId_"))
                {
                    studentIds.Add(Request[Request.Form.Keys[i]]);
                }
            }

            NewAlertViewModel model = new NewAlertViewModel();

            model.LoadRetentionAlertToBeSubmitted(studentIds, course);

            if (!string.IsNullOrEmpty(p))
            {
                model.PreviousStep = p;
            }

            return View(model);
        }

        [Authorize]
        [HttpGet]
        public ActionResult NewByCourse()
        {
            return View();
        }

        [Authorize]
        [HttpPost]
        public ActionResult NewByCourse(string txtCourse, string txtSection, string ddlSemester, string ddlYear)
        {
            return Redirect("~/alert/newstep2/?c=" + ddlYear + "-" + ddlSemester + "-" + txtCourse.ToUpper() + "-" + txtSection.ToUpper() + "&p=newbycourse");
        }

        [Authorize]
        [HttpGet]
        public ActionResult AlertSubmitted()
        {
            AlertSubmittedResultsModel model = new AlertSubmittedResultsModel();

            if (TempData["Results"] != null)
            {
                model = TempData["Results"] as AlertSubmittedResultsModel;
            }

            return View(model);
        }

        [Authorize]
        [HttpPost]
        public ActionResult AlertSubmitted(string course)
        {


            //got get all the posted data
            List<SubmitResult> results = new List<SubmitResult>();

            //get all the student Ids first
            List<string> studentIds = new List<string>();

            for (int i = 0; i < Request.Form.Keys.Count; i++)
            {
                if (Request.Form.Keys[i].StartsWith("studentId_"))
                {
                    studentIds.Add(Request[Request.Form.Keys[i]]);
                }
            }

            foreach (string studentId in studentIds)
            {
                //get each set of form values
                int studentIdVal = -1;
                DateTime lastAttended = DateTime.Now;

                if (int.TryParse(Request["studentId_" + studentId], out studentIdVal))
                {
                    var retentionAlert = new Lib.Models.RetentionAlertModel();

                    string facultyFirstName = Request["facultyFirstName_" + studentId];
                    string facultyMiddleName = Request["facultyMiddleName_" + studentId];
                    string facultyLastName = Request["facultyLastName_" + studentId];
                    string facultyEmail = Request["facultyEmailName_" + studentId];
                    string studentName = Request["studentName_" + studentId];

                    string concern = Request["concern_" + studentId];
                    string grade = Request["grade_" + studentId];
                    string comments = Request["comments_" + studentId];
                    string studentContact = Request["studentContact_" + studentId];
                    string instructorContact = Request["instructorContact_" + studentId];
                    string instructorId = Request["facultyId_" + studentId];

                    string bbGeneration = Request["chkBB_" + studentId];

                    int facultyId = -1;

                    int.TryParse(instructorId, out facultyId);

                    //string course = Request["course_" + studentId];
                    string courseNumber = string.Empty;
                    string sectionNumber = string.Empty;
                    string semester = string.Empty;
                    int year = -1;

                    string[] courseChunks = course.Split('-');

                    bool hasLastAttendedDate = false;

                    hasLastAttendedDate = DateTime.TryParse(Request["txtAttendDate_" + studentId], out lastAttended);

                    if (courseChunks.Length == 4)
                    {
                        courseNumber = courseChunks[2];
                        sectionNumber = courseChunks[3];
                        semester = courseChunks[1];

                        if (int.TryParse(courseChunks[0], out year))
                        {
                            if (retentionAlert.SaveRetentionAlert(studentIdVal, facultyFirstName, facultyMiddleName, facultyLastName, facultyEmail, facultyId, courseNumber, sectionNumber, semester, year,
                                (hasLastAttendedDate ? lastAttended : (DateTime?)null), concern, (!string.IsNullOrEmpty(grade) ? (grade == "Yes" ? true : false) : (bool?)null), comments,
                                (!string.IsNullOrEmpty(studentContact) ? (studentContact == "Yes" ? true : false) : (bool?)null),
                                (!string.IsNullOrEmpty(instructorContact) ? (instructorContact == "Yes" ? true : false) : (bool?)null), User.Identity.Name.Replace("@calbaptist.local", ""),
                                (!string.IsNullOrEmpty(bbGeneration) ? (bool?)true : null)))
                            {
                                results.Add(new SubmitResult { StudentID = studentId, StudentName = studentName, Successful = true });
                            }
                            else
                            {
                                results.Add(new SubmitResult { StudentID = studentId, StudentName = studentName, Successful = false });
                            }

CbuRetentionAlert.Web/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using CbuRetentionAlert.Web.Models;
using CbuRetentionAlert.Web.ViewModels;

namespace CbuStudentLookup.Web.Controllers
{
    [Authorize]
    public class HomeController : Controller
    {
        [Authorize]
        public ActionResult Index()
        {
            HomeViewModel model = new HomeViewModel();

            if (User.IsInRole("Admin"))
            {
                List<SelectListItem> items = new List<SelectListItem>();
                CbuRetentionAlert.Lib.Models.RetentionAlertModel vm = new CbuRetentionAlert.Lib.Models.RetentionAlertModel();
                var semesters = vm.GetSemesters();

                string semester = Request.Form["AdminAlerts.semester"];

                if (!string.IsNullOrEmpty(semester))
                {
                    string[] sem = semester.Split('-');

                    if (sem.Length == 2)
                    {
                        int year = DateTime.Now.Year;

                        int.TryParse(sem[1], out year);

                        model.LoadAdminAlerts(sem[0], year);

                        foreach (var s in semesters)
                        {
                            if (s.Year == year && s.Semester == sem[0])
                            {
                                items.Add(new SelectListItem { Text = s.Semester + " " + s.Year, Value = s.Semester + "-" + s.Year, Selected = true });
                            }
                            else
                            {
                                items.Add(new SelectListItem { Text = s.Semester + " " + s.Year, Value = s.Semester + "-" + s.Year });
                            }
                        }

                        ViewBag.Semesters = items;
                    }
                    else
                    {
                        model.LoadAdminAlerts(semesters[0].Semester, semesters[0].Year);

                        foreach (var s in semesters)
                        {
                            items.Add(new SelectListItem { Text = s.Semester + " " + s.Year, Value = s.Semester + "-" + s.Year });
                        }

                        ViewBag.Semesters = items;
                    }                    
                }
                else
                {
                    foreach (var s in semesters)
                    {
                        items.Add(new SelectListItem { Text = s.Semester + " " + s.Year, Value = s.Semester + "-" + s.Year });
                    }

                    ViewBag.Semesters = items;

                    model.LoadAdminAlerts(semesters[0].Semester, semesters[0].Year);
                }
            }
            else
            {
                var adUser = CbuAd.Lib.User.GetSingle(User.Identity.Name.Replace("@calbaptist.local", ""));

                //var adUser = CbuAd.Lib.User.GetUser("sclow");

                if (adUser != null && !string.IsNullOrEmpty(adUser.EmployeeId))
                {
                    int employeeId = -1;

                    if (int.TryParse(adUser.EmployeeId, out employeeId))
                    {
                        model.LoadAlerts(employeeId);
                    }
                }
            }

            return View(model);
        }
    }
}

CbuRetentionAlert.Web/Views/Home/DisplayTemplates/AdminAlert.cshtml
@model List<CbuRetentionAlert.Web.Models.StudentAlertModel>
@if (Model.Count > 0)
{
    <table class="table table-striped table-bordered">
        <thead>
            <tr>
                <th class="no-sort">
                     <div style="float:left;">
                    <h4>
                        Retention Alerts</h4>
                        </div>
                         <div style="float:right;">
            
           @using (Html.BeginForm("index", "home"))
           {
            <form action="/" method="post">
                <div style="float:left; margin-top:4px;"><b>Semester:</b> @Html.DropDownList("semester", ViewBag.Semesters as List<SelectListItem>)</div><div style="float:left;margin-top:4px;">&nbsp;<button class="btn btn-success">Change Semester</button></div> 
            </form>
           }
        </div>
                </th>
            </tr>
        </thead>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    <div class="navbar">
                        <div class="navbar-inner" style="margin-top: 8px;">
                            <div class="row-fluid" style="font-size: 1.2em; margin-left: -20px; margin-right: -20px;
                                padding: 10px;">
                                <div class="span2">
                                    <strong>Student ID:</strong><br />
                                    @item.Student.StudentId
                                </div>
                                <div class="span2">
                                    <strong>Student Name:</strong><br />@(item.Student.FirstName + (!string.IsNullOrEmpty(item.Student.MiddleName) ? " " + item.Student.MiddleName : string.Empty) + " " + item.Student.LastName)
                                </div>
                                <div class="span4">
                                    <strong>Student Email:</strong><br />
                                    <a href="mailto:@item.Student.Email">@item.Student.Email</a>
                                </div>
                                <div class="span2">
                                    <strong>Student Phone:</strong><br />@item.Student.Phone
                                </div>
                                <div class="span2">
                                    <strong>Admit Session & Year:</strong><br />@(item.Student.AdmitSemester + " " + item.Student.AdmitYear)
                                </div>
                            </div>
                        </div>
                    </div>
                    @foreach (var alert in item.Alerts)
                    {
                        <div class="row-fluid">
                            @{
                        string alertColorCSS = "alert alert-error-border";
                        string btnCSS = "btn btn-danger";

                        switch (alert.Status)
                        {
                            case "New":
                            case "Re-Opened":
                                btnCSS = "btn btn-danger";
                                alertColorCSS = "alert alert-error-border";
                                break;
                            case "Pending":
                                btnCSS = "btn btn-warning";
                                alertColorCSS = "alert alert-border";
                                break;
                            case "Completed":
                                btnCSS = "btn btn-success";
                                alertColorCSS = "alert alert-success-border";
                                break;
                        }
                            }
                            <div class="span11 @alertColorCSS" style="margin-left:10px; margin-right:-10px;">
                                @{                                    
                        if (alert.IsNewStudentTillDate.HasValue)
                        {
                            if (alert.IsNewStudentTillDate.Value >= DateTime.Now)
                            {
                                    <div class="row-fluid" style="margin-bottom: 8px;">
                                        <div class="span12 label label-inverse">
                                            <div style="width:100%; text-align:center; font-size:1.4em; margin-top:6px;">
                                                Admissions
                                            </div>
                                        </div>
                                    </div>
                            }
                        }
                                }
                                <div class="row-fluid">
                                    <div class="span3">
                                        <strong>Course: </strong>
                                        <br />@(alert.Course.Semester + " " + alert.Course.Year + " " + alert.Course.CourseNumber)</div>
                                    <div class="span3">
                                        <strong>Instructor: </strong>
                                        <br />@(alert.Instructor.FirstName + (!string.IsNullOrEmpty(alert.Instructor.MiddleName) ? " " + alert.Instructor.MiddleName : string.Empty) + " " + alert.Instructor.LastName)</div>
                                    <div class="span3">
                                        <strong>Instructor Email: </strong>
                                        <br />
                                        <a href="mailto:@alert.Instructor.EmailAddress">@alert.Instructor.EmailAddress</a></div>
                                    <div class="span3">
                                        <strong>Advisor: </strong>
                                        <br />@(!string.IsNullOrEmpty(alert.Advisor) ? alert.Advisor : "N/A")</div>
                                </div>
                                <div class="row-fluid" style="margin-top: 8px;">
                                    <div class="span3">
                                        <strong>Status: </strong>
                                        <br />@alert.Status</div>
                                    <div class="span3">
                                        <strong>Submitted: </strong>
                                        <br />@alert.Submitted.ToString()</div>
                                    <div class="span3">
                                        <strong>Submitted By: </strong>
                                        <br />@alert.SubmittedBy</div>
                                    <div class="span3">
                                        @if (alert.FollowUp.HasValue)
                                        {
                                            if (alert.FollowUp.Value < DateTime.Now)
                                            {
                                            <h2 class="label label-important" style="font-size: 1.2em; padding: 16px;">
                                                <i class="icon-flag"></i><strong>Follow up:</strong> @alert.FollowUp.Value.ToString()</h2>
                                            }
                                            else
                                            {
                                            <i class="icon-flag"></i> <strong>Follow up:</strong> <span>@alert.FollowUp.Value.ToString()</span>
                                            }
                                        }
                                    </div>
                                </div>
                            </div>
                            <div class="span1">
                                @Html.ActionLink("Manage Alert", "index", "alert", new { @id = alert.AlertId }, new { @class = btnCSS, @onclick = "showProcessing();" })
                            </div>
                        </div>
                    }
                </td>
            </tr>
        }
    </table>
}
else
{
    <div class="row">
        <div class="span12">
            <div class="well">
                <h3>
                    There are no retention alerts to display.</h3>
            </div>
        </div>
    </div>
}

CbuRetentionAlert.Web/Views/Home/DisplayTemplates/Alert.cshtml
@model List<CbuRetentionAlert.Web.Models.AlertOnlyModel>
@{
    if (Model.Count > 0)
    {
    <h4>
        Retention Alerts</h4>
    <table class="table table-striped table-bordered">
        <thead>
            <tr>
                <th>
                    Date
                </th>
                <th>
                    Student First Name
                </th>
                <th>
                    Student Last Name
                </th>
                <th>
                    Course
                </th>
                <th>
                    Instructor
                </th>
                <th>
                    Submitted By
                </th>
                <th>Status</th>
                <th>
                    Manage
                </th>
            </tr>
        </thead>
        <tbody>
            @{
        foreach (var alert in Model)
        {
                <tr>
                    <td>@alert.Submitted.ToString("MM/dd/yyyy hh:mm:ss tt")
                    </td>
                    <td>@alert.Student.FirstName
                    </td>
                    <td>@alert.Student.LastName
                    </td>
                    <td>@alert.Course.CourseNumber
                    </td>
                    <td>@(alert.Instructor.FirstName + " " + alert.Instructor.LastName)
                    </td>
                    <td>@alert.SubmittedBy
                    </td>
                    <td>@alert.Status</td>
                    <td>
                    @{
            string buttonClass = "btn btn-primary";
            
            switch(alert.Status)
            {
                case "New":
                case "Re-Opened":
                    buttonClass = "btn btn-danger";
                    break;
                case "Pending":
                    buttonClass = "btn btn-warning";
                    break;
                case "Completed":
                    buttonClass = "btn btn-success";
                    break;
            }
                        }
                        @Html.ActionLink("Manage Alert", "StudentAlert", "Alert", new { @Id = alert.Id }, new { @class = buttonClass })
                    </td>
                </tr>
        }
            }
        </tbody>
    </table>

    }
    else
    {
    <h3 class="muted">
        There are no retention alerts to display.</h3>
    <h3 class="text-info"> To get started, click the "Submit a New Retention Alert" button.</h3>
    }
}